# Generated by Django 4.0.4 on 2022-05-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='remark',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
